use crate::config::AppConfig;
use crate::queue::QueueState;
use crate::urls::LICENSING_BASE;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tauri::{AppHandle, Manager, State};
use tauri_plugin_opener::OpenerExt;
use tokio::sync::{watch, RwLock};

const LICENSE_KV_KEY: &str = "sys:license_token";

// ─── Token payload (decoded from base64 section of token) ────────────────────

#[allow(dead_code)]
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct LicensePayload {
    pub sub: i64,
    pub usr: String,
    pub sp:  bool,
    pub p:   String,
    pub iat: i64,
    pub exp: i64,
}

// ─── Verify response from server ─────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct VerifyResponse {
    pub valid:           bool,
    pub is_sponsor:      Option<bool>,
    pub is_owner:        Option<bool>,
    pub github_username: Option<String>,
    pub github_id:       Option<i64>,
    pub expires_at:      Option<String>,
    pub error:           Option<String>,
}

// ─── Commands ─────────────────────────────────────────────────────────────────

/// Retrieve the stored license token from the local database.
#[tauri::command]
pub async fn get_license_token(queue: State<'_, Arc<QueueState>>) -> Result<Option<String>, String> {
    let pool = queue.db.read().await;
    let val: Option<String> = sqlx::query_scalar(
        "SELECT value FROM kv_store WHERE key = ?",
    )
    .bind(LICENSE_KV_KEY)
    .fetch_optional(&*pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(val)
}

/// Persist a received license token to the local database.
#[tauri::command]
pub async fn set_license_token(
    token: String,
    queue: State<'_, Arc<QueueState>>,
) -> Result<(), String> {
    let pool = queue.db.read().await;
    sqlx::query(
        "INSERT INTO kv_store (key, value, updated_at) VALUES (?, ?, unixepoch())
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = unixepoch()",
    )
    .bind(LICENSE_KV_KEY)
    .bind(&token)
    .execute(&*pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(())
}

/// Clear the stored license token (logout).
#[tauri::command]
pub async fn clear_license_token(queue: State<'_, Arc<QueueState>>) -> Result<(), String> {
    let pool = queue.db.read().await;
    sqlx::query("DELETE FROM kv_store WHERE key = ?")
        .bind(LICENSE_KV_KEY)
        .execute(&*pool)
        .await
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Ask the server whether the stored token is still valid.
/// Returns VerifyResponse — caller checks `.valid`.
#[tauri::command]
pub async fn verify_license_token(token: String) -> Result<VerifyResponse, String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| e.to_string())?;

    let url = format!("{}/api/verify", LICENSING_BASE);
    let res = client
        .post(&url)
        .json(&serde_json::json!({ "token": token }))
        .send()
        .await
        .map_err(|e| format!("License verify request failed: {e}"))?;

    // The /api/verify contract always responds 200 with {valid: true|false} for
    // a request it could actually evaluate — a non-2xx here means the server
    // itself is broken (or unreachable through a proxy), not that the token
    // was rejected. Treat it like the network-failure case above (an Err the
    // caller's existing "server offline" handling already accounts for)
    // instead of synthesizing valid:false, which would wrongly look like an
    // explicit rejection and log the user out during a transient outage.
    if !res.status().is_success() {
        let status = res.status();
        let text = res.text().await.unwrap_or_default();
        return Err(format!("License server error ({status}): {text}"));
    }

    let body: VerifyResponse = res
        .json()
        .await
        .map_err(|e| format!("License verify parse error: {e}"))?;

    Ok(body)
}

/// Open the browser to begin the GitHub OAuth login flow.
/// `state` is a random hex string generated by the frontend to prevent CSRF.
/// Confirms the local callback server on port 24363 is actually listening
/// before opening the browser, so a login click never silently opens a
/// browser tab to a dead callback.
#[tauri::command]
pub async fn open_github_login(state: String, app: AppHandle) -> Result<(), String> {
    if state.len() < 16 || !state.chars().all(|c| c.is_ascii_alphanumeric()) {
        return Err("Invalid state parameter".to_string());
    }

    let ready = app.state::<crate::api::ApiReady>().inner().0.clone();
    // `ready` is a one-shot latch (true forever once the server has bound at
    // least once) — it doesn't track whether that server is *still* alive.
    // If it died in the meantime (crash, panic, anything), trusting the
    // latch alone would open the browser at a dead port with no warning.
    // A real, cheap connect attempt is the only way to know it's up *now*.
    let actually_listening = tokio::net::TcpStream::connect("127.0.0.1:24363").await.is_ok();
    if !actually_listening {
        ready.send(false).ok(); // correct the stale latch before restarting
        // kill_port_holder now refuses to touch our own PID, so this can't
        // clobber a server that's secretly still running under a race.
        let config   = app.state::<Arc<RwLock<AppConfig>>>().inner().clone();
        let shutdown = app.state::<Arc<watch::Sender<bool>>>().inner().clone();
        let rx       = shutdown.subscribe();
        let handle   = app.clone();
        let ready_for_start = ready.clone();
        tauri::async_runtime::spawn(async move {
            if let Err(e) = crate::api::start(config, handle, rx, ready_for_start).await {
                tracing::error!("API server restart failed: {e}");
            }
        });

        let mut ready_rx = ready.subscribe();
        if tokio::time::timeout(std::time::Duration::from_secs(5), ready_rx.wait_for(|v| *v))
            .await
            .is_err()
        {
            return Err("Could not start the local sign-in server (port 24363) — \
                it may be blocked by a firewall or already in use by another process."
                .to_string());
        }
    }

    let url = format!("{}/auth/github?state={}", LICENSING_BASE, state);
    app.opener()
        .open_url(&url, None::<&str>)
        .map_err(|e| format!("Failed to open browser: {e}"))?;

    Ok(())
}

// ─── GDPR self-service (Art. 15 export / Art. 17 erasure) ─────────────────────

/// Fetch the full GDPR export (Art. 15) for the signed-in account. Response
/// shape is server-defined (see GdprController::export) — returned as raw
/// JSON since the frontend only needs to pretty-print it.
#[tauri::command]
pub async fn gdpr_export(token: String) -> Result<serde_json::Value, String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| e.to_string())?;

    let url = format!("{}/api/gdpr/export", LICENSING_BASE);
    let res = client
        .post(&url)
        .bearer_auth(&token)
        .send()
        .await
        .map_err(|e| format!("GDPR export request failed: {e}"))?;

    if !res.status().is_success() {
        let status = res.status();
        let text = res.text().await.unwrap_or_default();
        return Err(format!("GDPR export failed ({status}): {text}"));
    }

    res.json::<serde_json::Value>()
        .await
        .map_err(|e| format!("GDPR export parse error: {e}"))
}

#[derive(Debug, Serialize, Deserialize)]
pub struct GdprEraseResponse {
    pub success: bool,
    pub message: String,
}

/// Request GDPR erasure (Art. 17) for the signed-in account. Owner accounts
/// are rejected by the server with a 403 — surfaced here as a plain Err so
/// the caller can show it directly.
#[tauri::command]
pub async fn gdpr_erase(token: String) -> Result<GdprEraseResponse, String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| e.to_string())?;

    let url = format!("{}/api/gdpr/erase", LICENSING_BASE);
    let res = client
        .post(&url)
        .bearer_auth(&token)
        .send()
        .await
        .map_err(|e| format!("GDPR erase request failed: {e}"))?;

    if !res.status().is_success() {
        let status = res.status();
        let text = res.text().await.unwrap_or_default();
        // Try to surface the server's {error, blocking_packages?} body directly
        // (e.g. the owner-account 403, or the 409 sole-ownership block).
        if let Ok(body) = serde_json::from_str::<serde_json::Value>(&text) {
            if let Some(err) = body.get("error").and_then(|v| v.as_str()) {
                let names: Vec<String> = body.get("blocking_packages")
                    .and_then(|v| v.as_array())
                    .map(|arr| arr.iter()
                        .filter_map(|p| p.get("name").and_then(|n| n.as_str()).map(String::from))
                        .collect())
                    .unwrap_or_default();
                return Err(if names.is_empty() {
                    err.to_string()
                } else {
                    format!("{err} ({})", names.join(", "))
                });
            }
        }
        return Err(format!("GDPR erase failed ({status}): {text}"));
    }

    res.json::<GdprEraseResponse>()
        .await
        .map_err(|e| format!("GDPR erase parse error: {e}"))
}
