use crate::config::AppConfig;
use crate::queue::QueueState;
use serde::{Deserialize, Serialize};
use std::sync::Arc;
use tauri::{AppHandle, Manager, State};
use tauri_plugin_opener::OpenerExt;
use tokio::sync::{watch, RwLock};

const LICENSING_BASE: &str = "https://dl.supers0ft.us/gdlvlreqbot/licensing";
const LICENSE_KV_KEY: &str = "sys:license_token";

// ─── Token payload (decoded from base64 section of token) ────────────────────

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct LicensePayload {
    pub sub: i64,
    pub usr: String,
    pub sp:  bool,
    pub p:   String,
    pub iat: i64,
    pub exp: i64,
}

// ─── Verify response from server ─────────────────────────────────────────────

#[derive(Debug, Serialize, Deserialize)]
pub struct VerifyResponse {
    pub valid:           bool,
    pub is_sponsor:      Option<bool>,
    pub github_username: Option<String>,
    pub expires_at:      Option<String>,
    pub error:           Option<String>,
}

// ─── Commands ─────────────────────────────────────────────────────────────────

/// Retrieve the stored license token from the local database.
#[tauri::command]
pub async fn get_license_token(queue: State<'_, Arc<QueueState>>) -> Result<Option<String>, String> {
    let pool = queue.db.read().await;
    let val: Option<String> = sqlx::query_scalar(
        "SELECT value FROM kv_store WHERE key = ?",
    )
    .bind(LICENSE_KV_KEY)
    .fetch_optional(&*pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(val)
}

/// Persist a received license token to the local database.
#[tauri::command]
pub async fn set_license_token(
    token: String,
    queue: State<'_, Arc<QueueState>>,
) -> Result<(), String> {
    let pool = queue.db.read().await;
    sqlx::query(
        "INSERT INTO kv_store (key, value, updated_at) VALUES (?, ?, unixepoch())
         ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = unixepoch()",
    )
    .bind(LICENSE_KV_KEY)
    .bind(&token)
    .execute(&*pool)
    .await
    .map_err(|e| e.to_string())?;
    Ok(())
}

/// Clear the stored license token (logout).
#[tauri::command]
pub async fn clear_license_token(queue: State<'_, Arc<QueueState>>) -> Result<(), String> {
    let pool = queue.db.read().await;
    sqlx::query("DELETE FROM kv_store WHERE key = ?")
        .bind(LICENSE_KV_KEY)
        .execute(&*pool)
        .await
        .map_err(|e| e.to_string())?;
    Ok(())
}

/// Ask the server whether the stored token is still valid.
/// Returns VerifyResponse — caller checks `.valid`.
#[tauri::command]
pub async fn verify_license_token(token: String) -> Result<VerifyResponse, String> {
    let client = reqwest::Client::builder()
        .timeout(std::time::Duration::from_secs(10))
        .build()
        .map_err(|e| e.to_string())?;

    let url = format!("{}/api/verify", LICENSING_BASE);
    let res = client
        .post(&url)
        .json(&serde_json::json!({ "token": token }))
        .send()
        .await
        .map_err(|e| format!("License verify request failed: {e}"))?;

    let body: VerifyResponse = res
        .json()
        .await
        .map_err(|e| format!("License verify parse error: {e}"))?;

    Ok(body)
}

/// Open the browser to begin the GitHub OAuth login flow.
/// `state` is a random hex string generated by the frontend to prevent CSRF.
/// Ensures the local callback server on port 24363 is running before opening the browser.
#[tauri::command]
pub async fn open_github_login(state: String, app: AppHandle) -> Result<(), String> {
    if state.len() < 16 || !state.chars().all(|c| c.is_ascii_alphanumeric()) {
        return Err("Invalid state parameter".to_string());
    }

    // Check if the local callback server is listening; restart it if not.
    if tokio::net::TcpStream::connect("127.0.0.1:24363").await.is_err() {
        let config   = app.state::<Arc<RwLock<AppConfig>>>().inner().clone();
        let shutdown = app.state::<Arc<watch::Sender<bool>>>().inner().clone();
        let rx       = shutdown.subscribe();
        let handle   = app.clone();
        tauri::async_runtime::spawn(async move {
            if let Err(e) = crate::api::start(config, handle, rx).await {
                tracing::error!("API server restart failed: {e}");
            }
        });
        // Give it time to bind before the browser hits the callback
        tokio::time::sleep(std::time::Duration::from_millis(400)).await;
    }

    let url = format!("{}/auth/github?state={}", LICENSING_BASE, state);
    app.opener()
        .open_url(&url, None::<&str>)
        .map_err(|e| format!("Failed to open browser: {e}"))?;

    Ok(())
}
