ALTER TABLE config
    ADD COLUMN ws_enabled INTEGER NOT NULL DEFAULT 0;
ALTER TABLE config
    ADD COLUMN ws_port INTEGER NOT NULL DEFAULT 24364;
ALTER TABLE config
    ADD COLUMN ws_secret TEXT NOT NULL DEFAULT '';
